apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ia-chatbot.fullname" . }}
  labels:
    {{- include "ia-chatbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ia-chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ia-chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ia-chatbot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: health
              containerPort: {{ .Values.livenessProbe.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: health
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: health
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
